windowrule {
    name = thunar-float

    match:class = ^thunar$

    float = true
}

windowrule {
    name = thunar-size

    match:class = ^thunar$

    size = 1100 600
}

windowrule {
    name = firefox-workspace

    match:class = ^(firefox)$

    workspace = 1
}

windowrule {
    name = firefox-monitor

    match:class = ^(firefox)$

    move = monitor HDMI-A-1
}
